### ISSUE TITLE
Some items are unobtainable in survival

### ISSUE THREAD

**Issue by pxlreader** [timelord1102/Perfact-Parity-Pale-Garden#3]
-Pale oak leaves, pale hanging moss and pale oak door not dropping anything when mined (tested w/ all the tools w/ & w/out silk touch). 

-Since pale oak leaves doesn't drop anything, you can't get sapling through it either.

-Pale hanging moss doesn't appear even in creative inventory (only obtainable through command or pick block hotkey).

-All resin blocks does drop when mined but resin brick and all its variants are unobtainable because resin clump doesn't get smelted.

I'm on version 1.21.1

Mod list:
-Perfect Parity: The Garden Awakens Edition
-Perfect Parity: Spring To Life Edition
-TerraBlender
-Continuity
-Sodium

![Image](https://github.com/user-attachments/assets/95ce1ebe-5b88-463d-bba8-18e2c09f450c)

![Image](https://github.com/user-attachments/assets/fdf52673-4258-471e-8f76-77fd8e486a28)

**Comment by timelord1102** [comment]
Jesus, idk how I overlooked all that. Guess that's what happens when you code at 2am. I'll fix this asap

**Comment by timelord1102** [comment]
Fixed!

**Comment by pxlreader** [comment]
Thanks a lot!
I've tested it again, most of them are now obtainable!
Although pale hanging moss and pale oak door are still bugged (still doesn't drop when mined in survival).

**Comment by timelord1102** [comment]
I noticed pale oak door myself, that should be fixed. Seems the issue is fabric datagen fails randomly for random items because I'm using the Minecraft namespace. I'll fix pale hanging moss later today.
